version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: waiting-queue-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    restart: unless-stopped
    networks:
      - waiting-queue-network

volumes:
  redis-data:

networks:
  waiting-queue-network:
    driver: bridge